#关系型数据库配置
[mysql]
host = "127.0.0.1"
port = 3306
database = "bytedance"
username = "root"
password = "123456"
charset = "utf8mb4"
parse_time = true
loc = "Local"

#redis，用于存储每个用户是否对某个视频点赞，以及关注了某个人（主要用于反馈前端情况，比如点了赞后会变成红心
[redis]
ip = "127.0.0.1"
port = 6379
database = 0

#记录当前服务器的ip和启动端口号，当前服务器的ip用于生成对应的视频链接地址
[server]
ip = "115.156.212.181"
port = 8080