[mysql]
host = "127.0.0.1"
port = 3306
database = "bytedance"
username = "root"
password = "123456"
charset = "utf8mb4"
parse_time = true
loc = "Local"

[redis]
ip = "127.0.0.1"
port = 6379
database = 0

[server]
ip = "115.156.212.181"
port = 8080